Feature/checkstyle
r3back/the-core pull request #31
Opened 2023-08-06 18:12 UTC by Zanganito

2023-08-06 18:13 UTC, Zanganito commented
Adds an changes

2023-08-08 23:23 UTC, Zanganito commented
Please, can you  checks this new changes? thanks.

2023-08-08 23:25 UTC, r3back commented
Sorry I can't man

2023-08-08 23:48 UTC, Zanganito commented
it's okay :(

2023-09-10 02:06 UTC, r3back requested changes

2024-11-10 02:10 UTC, closed without merging